### ISSUE TITLE
select function

### ISSUE THREAD

**Issue by Mineru98** [rulyox/oqo#1]
안녕하세요.
페북 생활코딩 글 보고 관심이 생겨서 이슈 하나 생성하고 갑니다!

개인적으로 select 부분에서 array string 방식 말고 string type을 공백을 split 해서 사용하면 어떨까 생각이 드네요.
제가 주고 사용하는게 Mongo DB인데 DB가 Object 구조로 된 이 라이브러리랑 비슷하게 구현인 되어있는걸로 아는데
Mongo DB 문법에서는 Array를 안쓰고 공백을 split 분할점으로 하고 필드 구분을 하는걸로 알고 있습니다.

```typescript
select(selectList: string): OQO {
    this.selectList = selectList.split(" ");
    return this;
 }
// 코드 위치 https://github.com/rulyox/oqo/blob/master/lib/oqo.ts#L11
```

**Comment by rulyox** [comment]
의견 감사합니다.
참고하도록 하겠습니다.
